### ISSUE TITLE
func `eat` return type

### ISSUE THREAD

**Issue by mzprog** [cvhariharan/Tiny-Basic#6]
https://github.com/cvhariharan/Tiny-Basic/blob/94171f8447becb209188e3711e81f45697a87f54/src/parser.c#L135

why eat returning `Token` data type , it's found but no use till now, i was planning to make it void.
but it's return the previous token, and i have no idea why

**Comment by cvhariharan** [comment]
This is to find operators like here [https://github.com/cvhariharan/Tiny-Basic/blob/94171f8447becb209188e3711e81f45697a87f54/src/parser.c#L183](https://github.com/cvhariharan/Tiny-Basic/blob/94171f8447becb209188e3711e81f45697a87f54/src/parser.c#L183)
